name: main
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.x
      - run: pip install mkdocs-material==8.3.3
      - run: mkdocs gh-deploy --force
