name: main
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3.1.0
        with:
          python-version: 3.10.x
      - run: pip install mkdocs-material==7.3.6
      - run: mkdocs gh-deploy --force
